[project]
name = "vibepdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cookies>=0.7.0",
    "pyyaml>=6.0.0",
    "cookiecutter>=2.1.0",
]
